import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme/theme";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import Product from "@/components/Product/Product";
import TrendingProducts from "@/components/TrendingProducts/TrendingProducts";
import Category from "@/components/Category/Category";
import FilterProducts from "@/components/FilterProducts/FilterProducts";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spider",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
